### PR TITLE
🐛Refresh solutionentries and open solutions without an internal pe

### LINKED ISSUE #1752: 🐛 BPMN Studio Only Works When "Internal" Process Engine Is Running
## Description

When the "internal" process engine (default: `http://localhost:8000`) of the BPMN Studio is not running the Studio does not work.

That means that the web version only works when a process engine is running on the url configured via `processEngineRoute` in `aurelia_project/environemnt/dev.ts`.

## Reproduction

- Make sure no process engine is running on `http://localhost:8000`
- Run the web version of the BPMN Studio
- Try to connect another process engine
- **Notice that the Studio is unable to connect to another process engine**

### LINKED ISSUE #1772: 🐛BPMN-Studio doesn't check Authority from reconnected PE
## Description

Currently BPMN-Studio notices correctly if a PE is "down" and reconnects the PE automatically if it is still in the Solution Explorer.

Sadly it doesn't check if the Authority of the PE has changed. 

## Reproduction

- Start a local PE with the Authority set to `localhost:6000`.
- Start an IdentityServer at `localhost:5000`.
- Connect the PE to BPMN-Studio.
- Kill the PE (Strg + C in Terminal)
- BPMN-Studio now should notice that the PE is offline.
- Alter the Authority of the PE to `localhost:5000`.
- Start the PE again.
- Try to login into the PE from the Studio. 

## Possible solution

Set the Authority after the PE reconnects.

## My setup

- BPMN-Studio: 5.8.0

### LINKED ISSUE #1775: 🐛 Studio Does Not Update Runtime Version
## Description

When updating a runtime that is connected to an opened BPMN Studio the BPMN Studio does not update the runtime version when hovering above the solution entry.

### PR DESCRIPTION
**Pull request by alexanderkasten**
## Changes

1. Update the runtime version and authority while fetching the processmodels.
2. Fix bug where the studio does not add solutions if the internal processengine is not running

## Issues

Closes #1775 
Closes #1772 
Closes #1752 

PR: #1781 

## How to test the changes

> Describe how others can test your changes (not required when fixing typos, linter errors and such)

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -17,19 +17,21 @@ export function configure(aurelia: Aurelia): void {
   if ((window as any).nodeRequire) {
     const ipcRenderer: any = (window as any).nodeRequire('electron').ipcRenderer;
     const newHost: string = ipcRenderer.sendSync('get_host');
-
+    const ProcessEngineVersion: string = ipcRenderer.sendSync('get_version');
```
Comment (SteffenKn) [inline src/main.ts]: Typo:

```suggestion
    const processEngineVersion: string = ipcRenderer.sendSync('get_version');
```

File: src/main.ts [hunk 2]
```diff
@@ -17,19 +17,21 @@ export function configure(aurelia: Aurelia): void {
...
     /**
      * Currently the internal PE is always connected via http.
      * This will be subject to change.
      */
     const processEngineBaseRouteWithProtocol: string = `http://${newHost}`;
 
     localStorage.setItem('InternalProcessEngineRoute', processEngineBaseRouteWithProtocol);
+    localStorage.setItem('InternalProcessEngineVersion', ProcessEngineVersion);
```
Comment (SteffenKn) [inline src/main.ts]:
```suggestion
    localStorage.setItem('InternalProcessEngineVersion', processEngineVersion);
```

File: src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts [hunk 3]
```diff
@@ -306,6 +312,28 @@ export class SolutionExplorerSolution {
...
+      const authorityResponse = await fetch(`${this.displayedSolutionEntry.uri}/security/authority`);
+      const authorityJsonBody = await authorityResponse.json();
+
+      this.displayedSolutionEntry.authority = authorityJsonBody.authority;
+      this.displayedSolutionEntry.processEngineVersion = responseJsonBody.version;
+      this.globalSolutionService.addSolutionEntry(this.displayedSolutionEntry);
+      this.signaler.signal('update-version-icon');
+    } catch (error) {
+      throw error;
+    }
```
Comment (SteffenKn) [inline src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts]: Das try/catch macht so doch quasi... nichts.
