### PR TITLE
🐛 Fix Open Single Diagram Dialog

### LINKED ISSUE #990: When opening a single diagram, the File Type is set to "Custom File" instead of "bpmn"
#### Describe your issue

In the windows open file dialog, the File type for opening files is set to "Custom File" instead of "bpmn". 

#### How can others reproduce the issue?

* Try to open a single diagram with BPMN Studio for Windows
* Look at the Filetype in the Open File Dialog window. 

screen shot 2018-09-28 at 09 09 49

This should be related to: #805 and *should* be resolved, when we update the electron version. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by SteffenKn**
**Changes:**

1. Use Electron Dialog for Opening Single Diagrams

**Issues:**

Closes #990

PR: #1021

## How can others test the changes?

- Open up the BPMN-Studio (both, Windows and Mac)
- Click on the Open Single Diagram Button
- **(Mac) Notice that it is still working as before**
- **(Windows) Notice that the filetype filter now displays "BPMN (.bpmn,.xml)".**

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts [hunk 1]
```diff
@@ -114,7 +115,20 @@ export class SolutionExplorerPanel {
...
+  /**
+   * Handles the file input change event for the single file input.
+   * @param event An event that holds the files that were "uploaded" by the user.
+   * Currently there is no type for this kind of event.
+   */
+  public async onSingleDiagramInputChange(event: IInputEvent): Promise<void> {
+    const uri: string = event.target.files[0].path;
+    this.singleDiagramInput.value = '';
+
+    return this._openSingleDiagramOrDisplyError(uri);
```
Comment (robpal94) [inline src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts]: Typo in the Method's name

File: src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts [hunk 2]
```diff
@@ -114,7 +115,20 @@ export class SolutionExplorerPanel {
...
+  }
+
   public async openDiagram(): Promise<void> {
+    // this.singleDiagramInput.click();
```
Comment (robpal94) [inline src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts]: Can this unused code be removed?

Comment (SteffenKn) [reply src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts]: This was unused because I reverted a previous commit. This will now be used.

**Comment by SteffenKn** [comment]
@Paulomart Fixed the browser version.

File: src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts [hunk 3]
```diff
@@ -25,6 +25,8 @@ export class SolutionExplorerPanel {
   private _eventAggregator: EventAggregator;
   private _notificationService: NotificationService;
   private _router: Router;
+  // TODO: Add typings
+  private _ipcRenderer: any;
```
Comment (Paulomart) [inline src/modules/solution-explorer/solution-explorer-panel/solution-explorer-panel.ts]: A nice typing would be `any | null` to its clear that this can be null
