### PR TITLE
🐛 Fix Diff Against Deployed Diagram

### LINKED ISSUE #1241: 🐛 Changing Diagram Does Not Always Work Correctly.
#### Describe your issue

When changing from a local stored diagram to a deployed diagram with the same name, the BPMN-Studio will not change the Diagram. Instead it just keeps working as if the diagram was never changed.

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Open a local diagram
- Deploy the diagram
- Change the deployed diagram
- Change back to the local diagram
- **Notice that the BPMN-Studio will neither show the 'Document Contains Changes'-Modal nor change the diagram.**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by SteffenKn**
**Changes:**

1. Fix diff against deployed diagram
2. Prevent fitToViewport When Diagram is Not Displayed
3. Fix navigation between two diagrams with the same name

**Issues:**

Closes #1241

PR: #1252 

## How can others test the changes?

- Open up the BPMN-Studio 
- Go to the Detail View of any diagram 
- Go to the Diff View
- Click on the icon
- Select a ProcessEngine
- **Notice that it will display the diff as it should.**

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/modules/design/bpmn-diff-view/bpmn-diff-view.ts [hunk 1]
```diff
@@ -233,6 +232,42 @@ export class BpmnDiffView {
     rightCanvas.viewbox(changedViewbox);
   }
 
+  private async _updateDeployedXml(): Promise<boolean> {
+    const activeSolutionEntry: ISolutionEntry = this._solutionService.getRemoteSolutionEntries().find((remoteSolution: ISolutionEntry): boolean => {
```
Comment (Vyperus) [inline src/modules/design/bpmn-diff-view/bpmn-diff-view.ts]: You could just call `getSolutionForUri()` here i guess.

File: src/modules/design/bpmn-diff-view/bpmn-diff-view.ts [hunk 2]
```diff
@@ -233,6 +232,42 @@ export class BpmnDiffView {
...
+    });
+
+    const diagram: IDiagram = await getXmlFromDeployed();
+
+    const diagrammIsNotDeployed: boolean = diagram === undefined;
+    this.deployedXml = (diagrammIsNotDeployed)
+                                    ? undefined
+                                    : diagram.xml;
+
+    const diffingAgainstDeployed: boolean =  this._diffDestination !== 'lastSaved';
```
Comment (Vyperus) [inline src/modules/design/bpmn-diff-view/bpmn-diff-view.ts]:
```suggestion
    const diffingAgainstDeployed: boolean = this._diffDestination !== 'lastSaved';
```

File: src/modules/design/design.scss [hunk 3]
```diff
@@ -15,6 +15,21 @@
   margin-right: 36px;
 }
 
+.design__diff-destination-button {
```
Comment (Vyperus) [inline src/modules/design/design.scss]: Shouldn't this be in the "diff" module itself?

File: src/modules/design/design.ts [hunk 4]
```diff
@@ -161,10 +151,12 @@ export class Design {
...
 
-  public toggleDiffDestination(): void {
-    this.diffDestinationIsLocal = !this.diffDestinationIsLocal;
-    const diffDestination: string = this.diffDestinationIsLocal ? 'local' : 'deployed';
+  public determineActivationStrategy(): string {
+
+    return activationStrategy.invokeLifecycle;
+  }
 
+  public toggleDiffDestination(diffDestination: string): void {
```
Comment (Vyperus) [inline src/modules/design/design.ts]:
```suggestion
  public setDiffDestination(diffDestination: string): void {
```

File: src/modules/design/design.scss (hunk 3 above)
Comment (SteffenKn) [reply src/modules/design/design.scss]: Since the button belongs to the design view I don't think that the CSS class should belong to the diff module.

File: src/modules/design/bpmn-diff-view/bpmn-diff-view.ts [hunk 5]
```diff
@@ -233,6 +232,42 @@ export class BpmnDiffView {
...
+    });
+
+    const activeSolutionEntryNotFound: boolean = activeSolutionEntry === undefined;
+    if (activeSolutionEntryNotFound) {
+      return false;
+    }
+
+    const getXmlFromDeployed: () => Promise<IDiagram> = (async(): Promise<IDiagram> => {
+      try {
+        return await activeSolutionEntry.service.loadDiagram(this.processModelId);
```
Comment (robpal94) [inline src/modules/design/bpmn-diff-view/bpmn-diff-view.ts]: Hmm, I would expect, that this method returns the actual xml and not the `IDiagram` object, where we have to extract the XML from first.

File: src/modules/design/bpmn-diff-view/bpmn-diff-view.ts [hunk 6]
```diff
@@ -233,6 +232,42 @@ export class BpmnDiffView {
...
+        return undefined;
+      }
+    });
+
+    const diagram: IDiagram = await getXmlFromDeployed();
+
+    const diagrammIsNotDeployed: boolean = diagram === undefined;
+    this.deployedXml = (diagrammIsNotDeployed)
+                                    ? undefined
+                                    : diagram.xml;
```
Comment (robpal94) [inline src/modules/design/bpmn-diff-view/bpmn-diff-view.ts]: We can omit this whole block, if `getXMLFromDeployed()` would directly return the xml as a `string` instead of an `IDiagram` object :).

File: src/modules/design/design.scss [hunk 7]
```diff
@@ -15,6 +15,21 @@
...
+  background: inherit;
+  border: none;
+}
+
+.design__diff-destination-button--disabled {
+  opacity: 0.2 !important;
+}
+
+
+.design__diff-destination-button:hover > .fas {
```
Comment (robpal94) [inline src/modules/design/design.scss]: Maybe I'm wrong, but I guess that our CSS Styleguide permits the usage of class selectors.

File: src/modules/design/design.ts [hunk 8]
```diff
@@ -235,6 +227,26 @@ export class Design {
     }
   }
 
+  public activeDiagramChanged(newValue: IDiagram, oldValue: IDiagram): void {
+    const activeDiagramDidNotChange: boolean = newValue.id === oldValue.id
```
Comment (robpal94) [inline src/modules/design/design.ts]:
```suggestion
    const activeDiagramDidNotChanged: boolean = newValue.id === oldValue.id
```

File: src/modules/design/design.ts [hunk 9]
```diff
@@ -235,6 +227,26 @@ export class Design {
...
+                                            && newValue.uri === oldValue.uri;
+    if (activeDiagramDidNotChange) {
```
Comment (robpal94) [inline src/modules/design/design.ts]:
```suggestion
    if (activeDiagramDidNotChanged) {
```

Comment (Vyperus) [reply src/modules/design/design.ts]: No, if you use "did" instead of "do" you are not adding the "-ed" on regular verbs.

File: src/modules/design/design.ts (hunk 8 above)
Comment (Vyperus) [reply src/modules/design/design.ts]: No, if you use "did" instead of "do" you are not adding the "-ed" on regular verbs.

File: src/modules/design/bpmn-io/bpmn-io.ts [hunk 10]
```diff
@@ -365,7 +366,13 @@ export class BpmnIo {
   private _fitDiagramToViewport(): void {
     const canvas: ICanvas = this.modeler.get('canvas');
 
-    canvas.zoom('fit-viewport');
+    const viewbox: IViewbox  = canvas.viewbox();
+
+    const diagramIsVisible: boolean = viewbox.height > 0 && viewbox.width > 0;
+
+    if (diagramIsVisible) {
```
Comment (alexanderkasten) [inline src/modules/design/bpmn-io/bpmn-io.ts]: 👍

File: src/modules/design/bpmn-diff-view/bpmn-diff-view.ts (hunk 5 above)
Comment (SteffenKn) [reply src/modules/design/bpmn-diff-view/bpmn-diff-view.ts]: Should fix the name 👍

File: src/modules/design/design.scss (hunk 7 above)
Comment (SteffenKn) [reply src/modules/design/design.scss]: I think you mean child selectors, since class selectors are for example
```
.design__diff-destination-button {
...
}
```

Comment (SteffenKn) [reply src/modules/design/design.scss]: @Vyperus @Vyperus this is used to add the hover effect to both icons when hovering above the div class around them.
Maybe you can tell me how I can do this without the child selector, since I can't think of an alternative right now.
