### PR TITLE
🐛Fix solution explorer performance

### LINKED ISSUE #1671: 🐛Bad performance if more than 50 opened diagrams
## Description

The performance of the Studio and especially the SolutionExplorer decreases per opened diagram noticeable. 

## Reproduction

- open more than 50 diagrams
- scroll with the solution explorer

## My setup

alpha 33

### PR DESCRIPTION
**Pull request by alexanderkasten**
## Changes

1. Fix SolutionExplorer performance bug

Before:
before

After:
after

## Issues

Closes #1671 

PR: #1673 

## How to test the changes

- open several diagrams (at least 50)
- scroll through the SolutionExplorer
- open a diagram and move it

### CODE REVIEW

File: src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts [hunk 1]
```diff
@@ -134,6 +141,18 @@ export class SolutionExplorerSolution {
       this.eventAggregator.subscribe('router:navigation:success', () => {
         this.updateSolutionExplorer();
       }),
+
+      this.eventAggregator.subscribe(environment.events.differsFromOriginal, async (isDiagramChanged: boolean) => {
```
Comment (alexanderkasten) [inline src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts]:
```suggestion
      this.eventAggregator.subscribe(environment.events.differsFromOriginal, (isDiagramChanged: boolean) => {
```
