### PR TITLE
🐛Fix unable to create property on usertask bug

### LINKED ISSUE #528: Error when creating form fields before property
#### Describe your issue

Getting an error when creating a user task and making settings in a specific order. Prevents me from adding properties(more specifically `camunda:property`) to the task.
 
 Here is the error message:
```
basics.ts:69 Uncaught TypeError: Cannot read property 'values' of undefined
    at BasicsSection.addProperty (basics.ts:69)
    at CallScope.evaluate (invocation_container.ts:23)
    at Listener.callSource (invocation_container.ts:23)
    at Listener.handleEvent (invocation_container.ts:23)
    at HTMLDocument.handleDelegatedEvent (invocation_container.ts:23)
```
Refers to modules/property-panel/indextabs/extensions/sections/basics.
Happens when you produce form fields before properties (like the required `uiName: Form`).
#### How can others reproduce the issue?

Create a user task.
Add form fields.
Then add a property(or try, because that's when the error occurs.)

#### Possible solution

```xml
    <bpmn:userTask id="Task_14y4xxy" name="UserTaskName">
      <bpmn:extensionElements>
        <camunda:formData>
          <camunda:formField id="FormFieldId" type="string" />
        </camunda:formData>
        <camunda:properties>
          <camunda:property name="uiName" value="Form" />
        </camunda:properties>
      </bpmn:extensionElements>
    </bpmn:userTask>
```
This is how a usertask with formfield + property looks like.

The `_addProperty` function checks whether an extensionElement exists (which exists because I created the form fields). It deducts that because there is an `camunda:extensionElements`, there must be a camunda:properties as well(which is not the case and causes the error).
If I had not created the extensionElements with my formfields, it would have created it itself including `camunda:properties`.

In order to solve this, make a consistent flow.

addProperty:
1. if properties does not exist, call addProperties
2. add the actual property

addProperties:
1. if extensionElements does not exist, call addExtensionElements
2. add the properties element

etc.

As of now it goes in multiple directions, e.g _createExtensionElement() creates `camunda:properties`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #565: Name camunda:properties element correctly and consistently
#### Describe your issue

In the codebase there is the `IProperty` interface for `camunda:property` and `IPropertyElement` for `camunda:properties`.
Functions and variables are also named accordingly.

`IPropertyElement` sounds a lot like `camunda:property`. Everything is an element, might as well be `IProperty2`. Every single time I read that it confuses me.

relevant for pr #554 

#### Possible solution

Name it `IProperties` or `IPropertiesElement`.
The `Element` in the name is optional but seems useful.
The variable name `properties` could that way stand for `Array<IProperty>` and the variable name `propertiesElement` would stand for `IPropertiesElement`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
## What did you change?

This PR fixes the bug when trying to create properties on a usertask before creating formfields.

Fixes #528 correctly.
Closes #565 

## How can others test the changes?

- checkout the branch
- `au run`
- check if you can create properties on (user)tasks und other elements 

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts [hunk 1]
```diff
@@ -66,8 +66,9 @@ export class BasicsSection implements ISection {
 
     this._propertyElement = this._getPropertyElement();
 
-    if (this._propertyElement.values === undefined) {
-      this._propertyElement.values = [];
+    if (this._propertyElement === undefined) {
```
Comment (SteffenKn) [inline src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]: Move the business logic out of the If condition

File: src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts [hunk 2]
```diff
@@ -162,6 +163,12 @@ export class BasicsSection implements ISection {
     this._businessObjInPanel.extensionElements = extensionElements;
   }
 
+  private _createEmptyPropertyElement(): void {
+    const propertyValues: Array<IProperty> = [];
+    const extensionPropertyElement: IPropertyElement = this._moddle.create('camunda:Properties', {values: propertyValues});
+    this._businessObjInPanel.extensionElements.values.push(extensionPropertyElement);
```
Comment (SteffenKn) [inline src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]: Please improve readability by adding some space.

```
private _createEmptyPropertyElement(): 
  const propertyValues: Array<IProperty> = [];
  const extensionPropertyElement: IPropertyElement = this._moddle.create('camunda:Properties', {values: propertyValues});

  this._businessObjInPanel.extensionElements.values.push(extensionPropertyElement);
}
```

File: src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts [hunk 3]
```diff
@@ -162,6 +165,13 @@ export class BasicsSection implements ISection {
     this._businessObjInPanel.extensionElements = extensionElements;
   }
 
+  private _createEmptyPropertyElement(): void {
+    const propertyValues: Array<IProperty> = [];
+    const extensionPropertyElement: IPropertyElement = this._moddle.create('camunda:Properties', {values: propertyValues});
```
Comment (cmg-dev) [inline src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]: This is a good example for how a lambda or smaller function can increase the readability:

```ts
const emptyProperty: Array<IProperty> = [];
const propertyElement =
  () => this._moddle.create('camunda:Properties', {values: emptyProperty});

const extensionPropertyElement: IPropertyElement = propertyElement();
```

This is more readable, as it gives the things we want to do a nice name.

If you have even better names, feel free to use them.

File: src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts [hunk 4]
```diff
@@ -162,6 +165,13 @@ export class BasicsSection implements ISection {
...
+
+    this._businessObjInPanel.extensionElements.values.push(extensionPropertyElement);
```
Comment (cmg-dev) [inline src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]: same here; we can hide technical details like-- `this._businessObjInPanel.extensionElements.values.push`-- as this provides no actual benefit for the reader:

```ts
// We can even declare this way above the actual usage.
const addPropertyElement = element => this._businessObjInPanel.extensionElements.values.push(element)

(...)

addPropertyElement(extensionPropertyElement);
```

Isn't this better?!

Comment (cmg-dev) [reply src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]:
```ts
addPropertyElement(propertyElement());
```

File: src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts [hunk 5]
```diff
@@ -162,6 +165,19 @@ export class BasicsSection implements ISection {
     this._businessObjInPanel.extensionElements = extensionElements;
   }
 
+  private _createEmptyPropertyElement(): void {
```
Comment (LeoTT) [inline src/modules/property-panel/indextabs/extensions/sections/basics/basics.ts]: This is about a `camunda:properties` element, so the function name is misleading. If there was no `camunda:property` I would not care.

Same goes for the name of the `IPropertyElement`, will open an issue for that.
