### PR TITLE
♻️ Fix Download Menu On Windows

### LINKED ISSUE #647: When exporting a diagram, the export filetype is not correctly shown in the explorer window
#### Describe your issue
When exporting the diagram, the file type is always set to _all files (*.*)_. In a perfect world, it would be set to the filetype that the user wants to export. 

screen shot 2018-07-26 at 14 08 25

#### How can others reproduce the issue?
* Try to export a diagram
* Look at the filetypes dropdown menu

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #648: Title of the Explorer Windows contains the image's source string
#### Describe your issue
When exporting a diagram, the title of the explorer window contains the base64 encoded image. 
This should be replaces with a fixed string like _select destination_ or the diagram's name.

screen shot 2018-07-26 at 14 08 25

#### How can others reproduce the issue?
* Try to export a diagram
* Look at the title bar of the destination selection

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #805: 🐛 File Extensions missing when exporting the Diagram
Die Dateiendungen werden auf Windows nicht hinzugefügt

### PR DESCRIPTION
**Pull request by SteffenKn**
:tada: **Thanks for submitting this Pull Request**

Please provide a list including your changes.

To help us to create a meaningful Changelog, we agreed 
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.

Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:

---

**Changes:**

1. Fix Setting File Type on Export for Windows
2. Fix Title of Explorer Window When Exporting
3. Fix Missing File Extension on Windows

**Issues:**

Closes #647 
Closes #805 
Closes #648

PR: #825 

---

See the [examples](#example) for inspiration.

## How can others test the changes?

**On Windows:**

- Open up the BPMN-Studio
- Go to the Detail View of any diagram
- Export the diagram
- **Notice:**
	- the window title is: `Speichern unter`
	- the file type is set
	- when changing the name of the diagram, the extension will still be used

**On Mac:**

- Check if exporting is still possible

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: electron_app/electron.js [hunk 1]
```diff
@@ -269,6 +270,44 @@ Main._createMainWindow = function () {
     Main._window = null;
   });
 
+
+  const platformIsWindows = process.platform === 'win32';
+
+  if(platformIsWindows) {
```
Comment (LeoTT) [inline electron_app/electron.js]: Space missing.
```js
   if (platformIsWindows) { 
```

File: electron_app/electron.js [hunk 2]
```diff
@@ -269,6 +270,44 @@ Main._createMainWindow = function () {
...
+    Main._window.webContents.session.on('will-download', (event, downloadItem) => {
+      const defaultFilename = downloadItem.getFilename();
+
+      const fileTypeIndex = defaultFilename.lastIndexOf('.') + 1;
+      const fileExtension = defaultFilename.substring(fileTypeIndex);
+
+      const fileExtensionIsBPMN = fileExtension === 'bpmn';
+      const fileType = fileExtensionIsBPMN ? `BPMN (.${fileExtension})` : `Image (.${fileExtension})`;
```
Comment (LeoTT) [inline electron_app/electron.js]: Could drop the string templating in the first case.
```js
       const fileType = fileExtensionIsBPMN ? 'BPMN (.bpmn)' : `Image (.${fileExtension})`; 
```
