### PR TITLE
🐛 :bug: Check For XML File Signature Before Opening Diagrams

### LINKED ISSUE #560: 🐛 Almost Anything Can Be Added to the Process Solution Explorer
#### Describe your issue

You can add almost anything to the process solution explorer with the "Open Diagram"-button:
 

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Open the process solution explorer
- Go to the filesystem view
- Click on the "Open Diagram"-button
- Choose any file type you want

#### Possible solution

- One could add the "accept" attribute to the input, but this is currently not working for electron.
- Only valid files should be added to the Process Solution Explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by Paulomart**
## What did you change?

**Changes**:

- Add diagram validator service fluent API.
- Extract single diagram opening code into a single function.
- Only allow files with XML signature to be opened.

Closes #560

## How can others test the changes?

- Start BPMN Studio as electron app
- Open single diagram via solution explorer icon
- Open diagram via double click feature

If the diagram is already opened a message should state that.

If the diagram is not an xml file a message should state that.

If the diagram was loaded no message should be shown.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 1]
```diff
@@ -207,6 +211,35 @@ export class ProcessSolutionPanel {
...
+    }
+
+    this.openedSingleDiagrams.push(newDiagram);
+    this.navigateToDiagramDetail(newDiagram);
+
+    return true;
+  }
+
+  private _hasXMLFileSignature(content: string): boolean {
+    const xmlSignature: string = '<?xml ';
```
Comment (SteffenKn) [inline src/modules/process-solution-panel/process-solution-panel.ts]: I don't think that checking fro the xmlSignature is enough.
In my opinion we should check if it is a BPMN Diagram not just a xml file.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 2]
```diff
@@ -84,8 +83,13 @@ export class ProcessSolutionPanel {
 
       if (fileInfo.path) {
         const diagram: IDiagram = await this._solutionExplorerServiceFileSystem.openSingleDiagram(fileInfo.path, this._identity);
-        this.openedSingleDiagrams.push(diagram);
-        this.navigateToDiagramDetail(diagram);
+
+        try {
+          await this._openSingleDiagram(diagram);
+        } catch (error) {
+          this._notificationService.showNotification(NotificationType.ERROR, `Error loading diagram: ${error.message}`);
```
Comment (SteffenKn) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Please change the error message from

```
Error loading diagram: Input diagram is not a XML file.
```

to something like

```
Only diagrams can be opened.
```
since it is way easier to understand for normal users.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 3]
```diff
@@ -207,6 +211,35 @@ export class ProcessSolutionPanel {
...
 
+  private async _openSingleDiagram(newDiagram: IDiagram): Promise<boolean> {
+    const diagramWithSameURI: IDiagram = this._findURIObject(this.openedSingleDiagrams, newDiagram.uri);
+
+    const diagramIsAlreadyOpened: boolean = diagramWithSameURI !== undefined;
+
+    if (diagramIsAlreadyOpened) {
+      // When the diagram is already opened we just navigate to that.
+      this.navigateToDiagramDetail(diagramWithSameURI);
+      return false;
```
Comment (SteffenKn) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Please add some spacing to improve the readability.
```
this.navigateToDiagramDetail(diagramWithSameURI);

return false;
```

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 2 above)
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Why?

To hint about, that the Diagram ist not an propitiate format is very useful.

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 1 above)
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Indeed, but this is the first step.

We need:

1. A DiagramValidationService, that holds the rules, what a valid digram really is

I would suggest a similar interface like the export Service.

```ts
diagramValidationService(diagram)
  .isXML()
  .isBPMN()
  .isWhateverNeeded();
```

this holds the rules nice an neat. We will add a backend functionality later, that can also validate the diagram.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 4]
```diff
@@ -207,6 +211,35 @@ export class ProcessSolutionPanel {
...
+    }
+
+    const isNonXMLFile: boolean = !this._hasXMLFileSignature(newDiagram.xml);
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Lets treat it as a sentence:

```ts
const diagramIsNoXMLFile = (...);

if (diagramIsNoXMLFile)
(...)
```

Give it a try...

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 2 above)
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: This was more about the format of the error message.
We use more simple error message with more focus on what the user did wrong.
Imo `Only XML file can be loaded.` or `Selected File is not a XML file.` is still better than `Error loading diagram: Input diagram is not a XML file.`.

File: src/modules/diagram-validation-service/DiagramValidator.ts [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+    const flatterned: Promise<void> = allPromise
+      .then((promiseResults: Array<boolean>): void => {
+        const containsFalse: boolean = promiseResults.indexOf(false) !== -1;
+        if (containsFalse) {
+          throw new Error(errorMessage);
+        }
+      });
+
+    return flatterned;
```
Comment (cmg-dev) [inline src/modules/diagram-validation-service/DiagramValidator.ts]: Is `flatterned` a word:

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 2 above)
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: @SteffenKn Yeah, I agree with this.

I want the
>Only XML file can be loaded. or Selected File is not an XML file.
part ;)

Do it!

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 6]
```diff
@@ -154,15 +174,15 @@ export class ProcessSolutionPanel {
 
     this.singleDiagramInput.value = '';
 
-    const diagramIsAlreadyOpen: boolean = this._findURIObject(this.openedSingleDiagrams, newDiagram.uri) !== undefined;
+    try {
+      const diagramWasAlreadyOpen: boolean = !await this._openSingleDiagram(newDiagram);
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: diagramAlreadyOpen

use. this. name.

Don't use past tense please.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 7]
```diff
@@ -207,6 +227,30 @@ export class ProcessSolutionPanel {
...
+      this.navigateToDiagramDetail(diagramWithSameURI);
+
+      return false;
+    }
+
+    await this._diagramValidationService
+      .start(newDiagram.xml)
+      .isXML()
+      .isBPMN()
+      .throwIfError();
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: I like it.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 8]
```diff
@@ -207,6 +227,30 @@ export class ProcessSolutionPanel {
...
+
+    if (diagramIsAlreadyOpened) {
+      // When the diagram is already opened we just navigate to that.
+      this.navigateToDiagramDetail(diagramWithSameURI);
+
+      return false;
+    }
+
+    await this._diagramValidationService
+      .start(newDiagram.xml)
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: suggestion: 

name `start(newDiagram.xml)` just `validate(newDiagram.xml)`

**Comment by Paulomart** [comment]
grafik

grafik

File: src/contracts/diagram-validation-service/IDiagramValidator.ts [hunk 9]
```diff
@@ -0,0 +1,7 @@
+export interface IDiagramValidator {
+
+  isXML(): IDiagramValidator;
+  isBPMN(): IDiagramValidator;
+  throwIfError(): Promise<void>;
```
Comment (robpal94) [inline src/contracts/diagram-validation-service/IDiagramValidator.ts]: can we rename this to `validate()`? `throwIfError()` sounds a bit misleading.

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 7 above)
Comment (robpal94) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Im not sure if the user is aware, that he has to call the `throwIfError()` method at the end of this chain to actually _validate_ the loaded xml.

File: src/modules/diagram-validation-service/DiagramValidator.ts [hunk 10]
```diff
@@ -1,39 +1,26 @@
-import {IDiagramValidator} from '../../contracts';
+import { ValidationRules } from '../../../node_modules/aurelia-validation';
```
Comment (alexanderkasten) [inline src/modules/diagram-validation-service/DiagramValidator.ts]: Remove whitespaces

File: src/contracts/diagram-validation-service/IDiagramValidationService.ts [hunk 11]
```diff
@@ -0,0 +1,12 @@
+import {IDiagramValidator} from './index';
+
+export interface IDiagramValidationService {
+
+  /**
+   * Starts the validation of a xml string.
```
Comment (cmg-dev) [inline src/contracts/diagram-validation-service/IDiagramValidationService.ts]: XML

File: src/contracts/diagram-validation-service/IDiagramValidationService.ts [hunk 12]
```diff
@@ -0,0 +1,12 @@
...
+   *
+   * @param xml the xml to be validated.
```
Comment (cmg-dev) [inline src/contracts/diagram-validation-service/IDiagramValidationService.ts]: XML.

Capital The...

File: src/modules/diagram-validation-service/DiagramValidator.ts [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+    // Create an array with promises for all validation rules.
+    const validationsResultPromise: Array<Promise<boolean>> = ruleSet.rules
+      .map((validationRule: IDiagramValidationRule): Promise<boolean> => {
+        return validationRule(this._diagramXML);
+      });
+
+    const unifiedPromise: Promise<Array<boolean>> = Promise.all(validationsResultPromise);
+
+    // Create a single promise that will resolve when all validations succeed.
+    // It will reject with the ruleset error if some validation did not succeed.
```
Comment (cmg-dev) [inline src/modules/diagram-validation-service/DiagramValidator.ts]: > (...) error if one or more validation did not succeed.

File: src/modules/diagram-validation-service/DiagramValidationService.ts [hunk 14]
```diff
@@ -0,0 +1,44 @@
+import {
+  IDiagramValidationRules,
+  IDiagramValidationService,
+  IDiagramValidator,
+} from '../../contracts';
+import {DiagramValidator} from './DiagramValidator';
+
+export class DiagramValidationService implements IDiagramValidationService {
```
Comment (cmg-dev) [inline src/modules/diagram-validation-service/DiagramValidationService.ts]: Well we could add some documentation of the whereabouts of this and spent some time explaining things.

Don't you think @Paulomart ?!

Comment (Paulomart) [reply src/modules/diagram-validation-service/DiagramValidationService.ts]: wtf
