### PR TITLE
🐛Close Diagrams after Reload and Fix Importing Diagrams Several Times

### LINKED ISSUE #1007: 🐛 Ein per Doppelklick geöffnetes Diagram wird mehrfach hinzugefügt.
Das Diagramm wird drei mal oder öfter hinzugefügt

bildschirmfoto 2018-10-08 um 11 08 36

### LINKED ISSUE #1016: 🐛Only one opened single diagram after reload
#### Describe your issue

If you had opened several single diagrams and reload your bpmn-studio (CTRL/CMD+R) only one random diagram stays opened

#### How can others reproduce the issue?

- open some diagrams
- reload bpmn-studio
- look at the solution explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
**Changes:**

1. Remove second `open-file` event listener.
2. Add a check if bpmn-studio is started/loaded for the first time
3. Fix typo on a variable

**Issues:**

Closes #1007 
Closes #1016 

PR: #1027 

---

See the [examples](#example) for inspiration.

## How can others test the changes?

> Describe how others can test your changes (you can remove this section for typo fixes etc.)

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: electron_app/electron.js [hunk 1]
```diff
@@ -329,7 +333,7 @@ Main._createMainWindow = function () {
   // broken if we carry a file system link as the last item of the browser
   // history.
   Main._window.loadURL('/');
-
+
```
Comment (Paulomart) [inline electron_app/electron.js]: Undo whitespace change

File: electron_app/electron.js [hunk 2]
```diff
@@ -16,6 +16,7 @@ const openAboutWindow = require('about-window').default;
 // following code tells the frontend the name and content of that file;
 // this 'get_opened_file' request is emmitted in src/main.ts.
 let filePath;
+let studioIsFirstLoaded = true;
```
Comment (Paulomart) [inline electron_app/electron.js]: I would rename, `studio` is kinda strange.

File: electron_app/electron.js [hunk 3]
```diff
@@ -260,7 +261,12 @@ Main._initializeApplication = function () {
 
       // for non-windows
       app.on('open-file', (event, path) => {
-        filePath = path;
+        if (studioIsFirstLoaded === true) {
```
Comment (SteffenKn) [inline electron_app/electron.js]:
```
        filePath = studioIsFirstLoaded
                   ? path
				   : undefined;

		const studioNotFirstLoaded = !studioIsFirstLoaded;
		if (studioNotFirstLoaded) {
          answerOpenFileEvent(path);
        }
```
