### PR TITLE
🐛Fix Identity Server Redirect on Windows

### LINKED ISSUE #804: 🐛 War das Anmelden erfolgreich, wird man zurück zum BPMN-Studio geleitet.
Auf Windows mit dem IdentityServer auf dem Mac wird man nicht zurückgeleitet

### LINKED ISSUE #916: 🐛Redirecting from the Identity Server to BPMN Studio does not work
#### Describe your issue

Related to: https://github.com/process-engine/bpmn-studio/issues/804

On Windows, you can click on `login` and get redirected to the Identiy Server login page. After login and clicking `allow`, you are not redirected to BPMN - Studio anymore. 

screen shot 2018-09-07 at 14 58 25

#### How can others reproduce the issue?
* Start an Identity Server (local or remote) 
* Click on `Login`
* Login using the default credentials
* Try to click at `Yes, allow`
 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by Vyperus**
**Changes:**

1. Add handling for redirects from identity server on windows.

**Issues:**

Closes #916
Closes #804

PR: #923

---

See the [examples](#example) for inspiration.

## How can others test the changes?

> Describe how others can test your changes (you can remove this section for typo fixes etc.)

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: electron_app/electron.js [hunk 1]
```diff
@@ -22,7 +22,26 @@ Main._window = null;
...
+  const existingInstance = app.makeSingleInstance((argv, workingDirectory) => {
+    const noPathSet = argv[1] === undefined;
+
+    if (noPathSet) {
+      return;
+    }
+
+    const url = argv[1];
+    const isSignInRedirect = url.startsWith('bpmn-studio://signin-oidc');
+    const isSignOutRefirect = url.startsWith('bpmn-studio://signout-oidc');
```
Comment (alexanderkasten) [inline electron_app/electron.js]: Redirect

File: electron_app/electron.js [hunk 2]
```diff
@@ -22,7 +22,26 @@ Main._window = null;
...
+
+    if (isSignInRedirect || isSignOutRefirect) {
```
Comment (alexanderkasten) [inline electron_app/electron.js]: Redirect

File: electron_app/electron.js [hunk 3]
```diff
@@ -22,7 +22,30 @@ Main._window = null;
 Main.execute = function () {
 
   // All custom scheme notifications on Windows and Linux will try to create a new instance of the application
-  const existingInstance = app.makeSingleInstance((argv, workingDirectory) => {});
+  const existingInstance = app.makeSingleInstance((argv, workingDirectory) => {
+    if (argv[1] === undefined) {
+      return;
+    }
+
+    const url = argv[1];
```
Comment (cmg-dev) [inline electron_app/electron.js]:
```js
const firstArgumentGiven = (argv[1] !== undefined);

const url = (firstArgumentGiven) ? argv[1] : return;
```

How do you like this?

File: electron_app/electron.js [hunk 4]
```diff
@@ -22,7 +22,30 @@ Main._window = null;
...
+    const isSignInRedirect = url.startsWith('bpmn-studio://signin-oidc');
+    const isSignOutRedirect = url.startsWith('bpmn-studio://signout-oidc');
```
Comment (cmg-dev) [inline electron_app/electron.js]: this will not form a sentence...

I know you learned this, but why not this:

```js
const urlIsSignOutRedirect = url.startsWith('bpmn-studio://signout-oidc');
if (urlIsSignOutRedirect) {
(...)
```

same for the other variable.

File: electron_app/electron.js (hunk 3 above)
Comment (Vyperus) [reply electron_app/electron.js]: That return statement won't work.But I will extract the business rule anyway.
