### PR TITLE
:bug: Auto Refresh Process Solution Panel

### LINKED ISSUE #315: Process Solution Explorer does not refresh after changing baseroute
#### Describe your issue

After you have changed the baseroute to another ProcessEngine, the Process Solution Explorer does not refresh its process list.

bildschirmfoto 2018-05-18 um 14 14 08

#### How can others reproduce the issue?

- Start BPMN-Studio as Electron app
- change the baseroute to another ProcessEngine 
- open the Process Solution Explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
## What did you change?

This PR refreshs the Process Solution Panel when the backend route has changed.
Also the Process Solution Panel is scrollable now.

Closes #315 

## How can others test the changes?

- start bpmn-studio as electron app
- open the process solution explorer
- connect to another ProcessEngine
- see that the process solution panel is refreshed

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [ ] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 1]
```diff
@@ -5,18 +5,45 @@ import {
...
 
   public async attached(): Promise<void> {
+    this._subscriptions = [
+      this._eventAggregator.subscribe(AuthenticationStateEvent.LOGIN, () => {
+        this._refreshProcesslist();
+      }),
+      this._eventAggregator.subscribe(AuthenticationStateEvent.LOGOUT, () => {
+        this._refreshProcesslist();
+      }),
+      this._eventAggregator.subscribe('process-solution-panel--refresh', () => {
```
Comment (Paulomart) [inline src/modules/process-solution-panel/process-solution-panel.ts]: I would suggest not using the event aggregator here; Instead the panel should have a `windows.setInterval(...)` task that does it.
