### PR TITLE
🐛 Fix Diagram Creation When Solution Is Closed

### LINKED ISSUE #1023: 🐛 Error When Closing the Solution While Creating a Diagram
#### Describe your issue

When closing the solution while creating a diagram I get the following error message on every click:

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Open a solution
- Click on the add diagram button
- Close the solution
- **Notice that when clicking anywhere an error will be thrown**

#### Possible solution

- Cancel the creation when closing the solution

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by SteffenKn**
**Changes:**

1. Fix Diagram Creation When Solution Is Closed

**Issues:**

Closes #1023 

PR: #1024 

## How can others test the changes?

- Open up the BPMN-Studio 
- Open a solution
- Click on the add diagram button
- Close the solution
- **Notice that when clicking anywhere no error will be thrown anymore**

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts [hunk 1]
```diff
@@ -354,7 +354,14 @@ export class SolutionExplorerSolution {
 
     // Reset input field.
     this._diagramCreationState.currentDiagramInputValue = '';
-    this.createNewDiagramInput.value = '';
+
+    const hasCreateNewDiagramInputIsExisting: boolean = this.createNewDiagramInput !== undefined
```
Comment (Vyperus) [inline src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts]: I think `isCreatingNewDiagram` is a better name for this variable since it describes the state the solution explorer in in somewhat better.

**Comment by SteffenKn** [comment]
@Paulomart Do you mean the detach function?
That will not work since the detach function will be called after the code that throws the errors.
