### PR TITLE
🐛Fix Copy on Xml

### LINKED ISSUE #1280: 🐛 Copy & Search Disabled in XML View
#### Describe your issue

This was resolved once (#1102), bug reappeared for me.

Cmd-C and Cmd-F do not work in XML-View with BPMN-Studio(electron) for me.
_EDIT: My bad, Cmd-F does not exist for electron apps. We could implement a search feature, but I think that's a low-priority feature._

I cannot get much use out of XML without that.

#### What's your setup

- BPMN-Studio Version (`4.16.0`):
- OS (`OS X`):
- Electron version

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
**Changes:**

1. Add Keyboard Variable
2. Bind/Unbind The Keyboard Dependent on Which View You Are

**Issues:**

Closes #1280 

PR: #1283 

---

See the [examples](#example) for inspiration.

## How can others test the changes?

- open a diagram
- switch to xml view
- select some lines of xml 
- click cmd + c
- switch to an place where you like to paste the copied part
- paste it

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/modules/design/bpmn-io/bpmn-io.ts [hunk 1]
```diff
@@ -295,6 +299,10 @@ export class BpmnIo {
     this.savedXml = await this.getXML();
   }
 
+  public get keyboard(): IKeyboard {
```
Comment (LeoTT) [inline src/modules/design/bpmn-io/bpmn-io.ts]: Do we have to expose this and access it with view-model references?
Would very much prefer an event based approach here. 

If for some reason this structure needs to be, it would be better to expose as little as necessary imo. In this case I would rather make public functions `bindKeyboard` and `unbindKeyboard`. Again, would rather think about events here.

File: src/modules/design/bpmn-io/bpmn-io.ts [hunk 2]
```diff
@@ -544,7 +557,6 @@ export class BpmnIo {
       return;
     }
 
-    const keyboard: IKeyboard = this.modeler.get('keyboard');
     const editorActions: IEditorActions = this.modeler.get('editorActions');
     const backSpaceKeyCode: number = 8;
     const removeSelectedElements: ((key: IInternalEvent, modifiers: KeyboardEvent) => boolean) =
```
Comment (LeoTT) [inline src/modules/design/bpmn-io/bpmn-io.ts]: The current typing here is horrifying.
```ts
const removeSelectedElements: ((key: IInternalEvent, modifiers: KeyboardEvent) => boolean) =
  (key: IInternalEvent, modifiers: KeyboardEvent): boolean => {
```

Please turn it into the following(or extract the type).
```ts
// tslint:disable-next-line:no-typedef
const removeSelectedElements = (key: IInternalEvent, modifiers: KeyboardEvent): boolean => {
```

File: src/modules/design/bpmn-io/bpmn-io.ts [hunk 3]
```diff
@@ -59,6 +59,8 @@ export class BpmnIo {
   private _diagramPrintService: IDiagramPrintService;
   private _diagramIsInvalid: boolean = false;
 
+  private _keyboard: IKeyboard;
```
Comment (LeoTT) [inline src/modules/design/bpmn-io/bpmn-io.ts]: I suggest dropping the private variable.
Instance variables always make me think that there is some state being kept there.
Would prefer having `const keyboard: IKeyboard = this.modeler.get('keyboard');` twice.

File: src/modules/design/bpmn-io/bpmn-io.ts [hunk 4]
```diff
@@ -261,6 +261,19 @@ export class BpmnIo {
       this._eventAggregator.subscribe(environment.events.bpmnio.togglePropertyPanel, () => {
         this._togglePanel();
       }),
+
+      this._eventAggregator.subscribe(environment.events.bpmnio.bindKeyboard, () => {
```
Comment (robpal94) [inline src/modules/design/bpmn-io/bpmn-io.ts]: Just a question: couldn't we just unbind the keyboard if we leave the BPMN-IO View and bind it back, when we navigate to it? Im not sure if we really need to throw an Event for this since

Comment (Vyperus) [reply src/modules/design/bpmn-io/bpmn-io.ts]: We navigate to the "design"-module which descides which view to show us. 
All views are binded via show.bind, this way they never get "unloaded" as long as you stay on the "design"-module.
We could fix this by introducing child routers to those modules but this a bigger task than u might think.

Comment (alexanderkasten) [reply src/modules/design/bpmn-io/bpmn-io.ts]: @Vyperus Yes, but IMO thats not a bug, it is nice to have it like it is, because we have a lot of benefits like copying elements from one diagram to another etc.

Comment (Vyperus) [reply src/modules/design/bpmn-io/bpmn-io.ts]: I wouldn't see this as bug as well. But as a feature for the days to come ;)
