### PR TITLE
🐛 Fix Diagram Changes Indicator

### LINKED ISSUE #1718: 🐛 Changed Indicator is Sometimes Wrong
## Description

When changing between some diagrams the changed indicator is sometimes wrong.

## Reproduction

- Create two new diagrams in a local solution with names like "test" and "test a" or "abc" and "abc def"
> It is important that the names are the same up to the first space.
> You can also create only one diagram and duplicate it using the context menu.
- Make sure they are not opened as open diagrams
- Open one of them
- Add some changes
- Open the other one
- **Notice that the diagram indicator from the changed diagram will disappear.** 

or

- Checkout the `feature/make_diagrams_deployable_via_solution-explorer` branch
- Open a diagram
- Add some changes
- Deploy the diagram (without saving)
- **Notice that the diagram indicator from the local diagram will disappear.** 

## Possible solution

The bug occured after merging [this pr](https://github.com/process-engine/bpmn-studio/pull/1673).
The problem is that the diagram state gets updated for the wrong diagram in the ['isDiagramChanged'](https://github.com/process-engine/bpmn-studio/blob/develop/src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts#L494) function

## My setup

image

and

`feature/make_diagrams_deployable_via_solution-explorer`

### PR DESCRIPTION
**Pull request by SteffenKn**
## Changes

1.  Fix Diagram Changes Indicator

## Issues

Closes #1718 

PR: #1720

## How to test the changes

- Create two new diagrams in a local solution with names like "test" and "test a" or "abc" and "abc def"
> It is important that the names are the same up to the first space.
> You can also create only one diagram and duplicate it using the context menu.
- Make sure they are not opened as open diagrams
- Open one of them
- Add some changes
- Open the other one
- **Notice that the diagram indicator from the changed diagram will disappear.** 

or

- Open a diagram
- Add some changes
- Deploy the diagram (without saving)
- **Notice that the diagram indicator from the local diagram will disappear.**

### CODE REVIEW

File: src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts [hunk 1]
```diff
@@ -137,9 +134,13 @@ export class SolutionExplorerSolution {
     this.notificationService = notificationService;
     this.globalSolutionService = solutionService;
     this.openDiagramStateService = openDiagramStateService;
-    this.bindingSignaler = bindingSignaler;
     this.deployDiagramService = deployDiagramService;
     this.saveDiagramService = saveDiagramService;
+
+    this.diagramStateList = this.openDiagramStateService.loadDiagramStateForAllDiagrams();
```
Comment (ElRaptorus) [inline src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts]: Der Call hier wird mehrfach ausgeführt. Sollte vllt. besser in eine eigene Funktion ausgelagert werden, um die Maintanability zu erhöhen.

File: src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts [hunk 2]
```diff
@@ -249,6 +238,8 @@ export class SolutionExplorerSolution {
       this.ipcRenderer.removeListener('menubar__start_close_all_diagrams', this.closeAllDiagramsEventFunction);
       this.ipcRenderer.removeListener('menubar__start_save_all_diagrams', this.saveAllDiagramsEventFunction);
     }
+
+    this.openDiagramStateService.removeOnDiaagramStatesChangedListener(this.diagramStatesChangedCallbackId);
```
Comment (ElRaptorus) [inline src/modules/solution-explorer/solution-explorer-solution/solution-explorer-solution.ts]:
```suggestion
    this.openDiagramStateService.removeOnDiagramStatesChangedListener(this.diagramStatesChangedCallbackId);
```

File: src/services/solution-explorer-services/OpenDiagramStateService.ts [hunk 3]
```diff
@@ -76,6 +80,23 @@ export class OpenDiagramStateService {
...
+      // eslint-disable-next-line
+      callbackId = new Date().getTime().toString(36);
+    }
+
+    this.diagramStatesChangedCallbacks.set(callbackId, callback);
+
+    return callbackId;
+  }
+
+  public removeOnDiaagramStatesChangedListener(callbackId: string): void {
```
Comment (ElRaptorus) [inline src/services/solution-explorer-services/OpenDiagramStateService.ts]:
```suggestion
  public removeOnDiagramStatesChangedListener(callbackId: string): void {
```

File: src/services/solution-explorer-services/OpenDiagramStateService.ts [hunk 4]
```diff
@@ -76,6 +80,23 @@ export class OpenDiagramStateService {
     window.localStorage.removeItem(key);
   }
 
+  public onDiagramStatesChanged(callback): string {
+    // eslint-disable-next-line
+    let callbackId: string = new Date().getTime().toString(36);
```
Comment (ElRaptorus) [inline src/services/solution-explorer-services/OpenDiagramStateService.ts]: Warum nicht einfach über das `uuid` modul per `uuid.v4()` eine neue UUID generieren?

File: src/services/solution-explorer-services/OpenDiagramStateService.ts [hunk 5]
```diff
@@ -76,6 +80,23 @@ export class OpenDiagramStateService {
...
+    while (this.diagramStatesChangedCallbacks.has(callbackId)) {
+      // eslint-disable-next-line
+      callbackId = new Date().getTime().toString(36);
```
Comment (ElRaptorus) [inline src/services/solution-explorer-services/OpenDiagramStateService.ts]: s.o.
