### PR TITLE
🐛 Fix UserTask FormField type defaults to CustomType

### LINKED ISSUE #731: 🐛 When There Is a Form Field Without a Type the Bpmn-Studio Thinks Its Type Is Custom Type
#### Describe your issue

When there is a user task with a form field without type the BPMN-Studio thinks its type is custom type.

#### How can others reproduce the issue?

- Open up the BPMN-Studio 
- Go to the Detail View of any diagram 
- Add a user task
- Add a form field without a type
- Save the diagram
- Reload the page
- Notice that the type of the form field now is custom type

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by robpal94**
## What did you change?

Fixes #731 

This is more a _quickfix_. 
IMO we should discuss, if it should be possible for the user to save the diagram, if it contains a UserTask with a FormField, that has no associated type. 

## How can others test the changes?
* Create a UserTask
* Add a FormField
* Dont specify a form type
* Save the diagram
* Leave the Detail view
* Open the Diagram again
* The FormType of your added FormField should not be _custom type_. 

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [ ] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [ ] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/property-panel/indextabs/forms/sections/basics/basics.ts [hunk 1]
```diff
@@ -189,7 +189,21 @@ export class BasicsSection implements ISection {
...
+     * If the Form type is not defined, we can set it to null. If it is defined,
+     * assign the correct form type.
+     *
+     * TODO: Find out if this is the proper way to handle such case.
+     */
+    if (selectedFormHasType) {
+      this.selectedType = this._getTypeAndHandleCustomType(this.selectedForm.type);
+    } else {
+      this.selectedType = null;
+    }
```
Comment (cmg-dev) [inline src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: This is also a prime example, when to use a ternary operator.

```ts
this.selectedType = selectedFormHasType ?
        this._getTypeAndHandleCustomType(this.selectedForm.type) : null;
```

Comment (cmg-dev) [reply src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: Does this answer the TODO at line 199?
https://github.com/process-engine/bpmn-studio/pull/785/files#diff-4c746dc0d1b8c90f14a058041faf1b09R199

Comment (robpal94) [reply src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: > This is also a prime example, when to use a ternary operator.
@cmg-dev I wasn't sure, if it would look a bit _too complex_ using the ternary operator in this case

Comment (cmg-dev) [reply src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: Please use the ternary operator ;)

File: src/modules/property-panel/indextabs/forms/sections/basics/basics.ts [hunk 2]
```diff
@@ -189,21 +189,38 @@ export class BasicsSection implements ISection {
     this.validationController.validate();
 
     this.isFormSelected = true;
-    this.selectedType = this._getTypeAndHandleCustomType(this.selectedForm.type);
+
+    const selectedFormHasType: boolean = this.selectedForm.type !== undefined;
+    this.selectedType = selectedFormHasType
+                    ? this._getTypeAndHandleCustomType(this.selectedForm.type)
+                    : null;
```
Comment (cmg-dev) [inline src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: 👍

File: src/modules/property-panel/indextabs/forms/sections/basics/basics.ts [hunk 3]
```diff
@@ -189,21 +189,38 @@ export class BasicsSection implements ISection {
...
+      if (selectedTypeIsCustomType) {
+          const customTypeIsDefined: boolean = this.customType !== undefined;
+          return customTypeIsDefined
+                    ? this.customType
+                    : '';
+
+        } else {
+          return this.selectedType;
+        }
+    })();
```
Comment (cmg-dev) [inline src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: We can write this nicer, by simple rearranging:

```ts
const type: string = ((): string => {
    const selectedTypeIsNotCustomType: boolean =
      this.selectedType !== FormfieldTypes.custom_type;

    if (selectedTypeIsNotCustomType) {
      return this.selectedType;
    }
      
    const customTypeIsDefined: boolean = this.customType !== undefined;
    
    return customTypeIsDefined
                    ? this.customType
                    : '';
  })();
```

File: src/modules/property-panel/indextabs/forms/sections/basics/basics.ts [hunk 4]
```diff
@@ -189,21 +189,37 @@ export class BasicsSection implements ISection {
...
+        this.selectedType !== FormfieldTypes.custom_type;
 
-    if (this.selectedType === FormfieldTypes.custom_type) {
-      type = this.customType;
-    } else {
-      type = this.selectedType;
-    }
+      if (selectedTypeIsNotCustomType) {
+          return this.selectedType;
+        }
```
Comment (alexanderkasten) [inline src/modules/property-panel/indextabs/forms/sections/basics/basics.ts]: wrong indentation
