### PR TITLE
🐛Fix Double Click / Instance Handling on Windows

### LINKED ISSUE #646: A new BPMN Studio instance opens when double clicking a process definition
#### Describe your issue
When double clicking on a bpmn process definition, a new instance of the BPMN Studio opens and only shows the process definition view instead of the double clicked process. 

That only the Process List view open, when you double click a bpmn process definition also happens,
when the bpmn studio was not running before.

jul-26-2018 14-02-22

#### How can others reproduce the issue?
* Open BPMN Studio
* Double Click on a bpmn process definition
* See, that a new instance of the bpmn studio gets created

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #1310: 🐛 A New Instance Will Be Opened, If the User Opens a Bpmn File via File Association
When opening a `BPMN` File with the BPMN-Studio, a new instance will be started.

### PR DESCRIPTION
**Pull request by Vyperus**
With Version 4.0.0 the developers of Electron introduced some new functions that make the handling of instances in Windows much easier. This PR adds all changes needed to use the new Functions and therefore fix the double click feature on Windows.

**Changes:**

1. Add the correct functionality to handle instances and the double click on windows.

**Issues:**

Closes #1310 
Closes #646 

PR: #PullRequest

## How can others test the changes?

1. Build BPMN-Studio on Windows.
2. Install it.
3. Start it via double click on a .bpmn file.
4. Double click on another file.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

### CODE REVIEW

File: electron_app/electron.js [hunk 1]
```diff
@@ -34,61 +34,53 @@ Main._window = null;
...
-  if (existingInstance) {
-    // Quit the new instance if required
-    app.quit();
+        answerOpenFileEvent(filePath)
+      }
 
-  } else {
-    // If this is the first instance then start the application
-    Main._startInternalProcessEngine();
+      if (argumentIsSignInRedirect || argumentIsSignOutRedirect) {
```
Comment (cmg-dev) [inline electron_app/electron.js]:
```suggestion
      const argumentContainsRedirect = argumentIsSignInRedirect || argumentIsSignOutRedirect;
      if (argumentContainsRedirect) {
```
