### PR TITLE
✨ :sparkles: Add basic functions to modeler and electron

### LINKED ISSUE #231: ✨Create Basic Usability
## Describe your issue

The basic functions of:

* Copy
* Paste
* Cut
* Undo
* Redo

do not work!

## How can others reproduce the issue?

This is obvious.

## Possible solution

Implement those functions!

## What's your setup

Don't care.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
## What did you change?

This PR adds the basic function described in #231

Closes #231 

## How can others test the changes?

- start bpmn-studio 
- navigate to detail view of a process
- select an element with mouseclick or select all with `cmd+a`
- use `cmd+c` to copy
- move the mouse and use `cmd+v` to paste the element(s)
- undo it with `cmd+z`
- redo it with `cmd+shift+z`

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/bpmn-io/bpmn-io.ts [hunk 1]
```diff
@@ -80,6 +80,7 @@ export class BpmnIo {
       moddleExtensions: {
         camunda: bundle.camundaModdleDescriptor,
       },
+      keyboard: { bindTo: document },
```
Comment (cmg-dev) [inline src/modules/bpmn-io/bpmn-io.ts]: yay. danke ;)
