### PR TITLE
🐛 Fix Diagram Name Validation For Escape Characters

### LINKED ISSUE #802: 🐛Escaping character in diagram title breaks the modeler
#### Describe your issue

When using `>` or `"` as diagramname (filename) it brokes everything.

```json
browser-raw.js:93 Unhandled rejection Error: no definitions loaded
    at Modeler.Viewer.saveXML (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:57167:19)
    at file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2084:39
    at Promise._execute (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2197:10)
    at BpmnIo.<anonymous> (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2083:37)
    at step (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28847:23)
    at Object.next (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28828:53)
    at file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28822:71
    at Promise._execute (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2197:10)
    at __awaiter (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28818:12)
    at BpmnIo.getXML (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2079:20)
    at BpmnIo.<anonymous> (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2067:45)
    at step (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28847:23)
```

#### How can others reproduce the issue?

Use `>` or `"` as diagram name.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by SteffenKn**
:tada: **Thanks for submitting this Pull Request**

Please provide a list including your changes.

To help us to create a meaningful Changelog, we agreed 
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.

Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:

---

**Changes:**

1. Check if diagram name is alphanumeric

**Issues:**

Closes #802

PR: #816 

---

See the [examples](#example) for inspiration.

## How can others test the changes?

- Open up the BPMN-Studio
- Open a solution via Solution Explorer
- Try to create a new diagram with a name that includes " or >

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 1]
```diff
@@ -89,7 +89,69 @@ export class ProcessSolutionPanel {
 
         return diagramWithIdDoesNotExists;
       })
-      .withMessage('A diagram with that name already exists.');
+      .withMessage('A diagram with that name already exists.')
+      .satisfies((input: string) => {
+        const regExpList: any = {
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Hier fehlt mir ein Typ.

`dict<IUserInputValidationRule>`

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 2]
```diff
@@ -89,7 +89,69 @@ export class ProcessSolutionPanel {
...
+          silesian: /^[ąłńóżćśůź]+$/i,
+          kashubian: /^[ąłńóżãéëòôù]+$/i,
+          slovene: /^[čšž]+$/i,
+          croatia: /^[čšžćđ]+$/i,
+          czech: /^[čšžáďéěňóřťúůý]+$/i,
+          slovak: /^[čšžáäďéíľĺňóôŕťúý]+$/i,
+          latvian: /^[čšžāēģīķļņōŗū]+$/i,
+          lithuanian: /^[ąęėįųūčšž]+$/i,
+          vietnamese: /^[đàảãáạăằẳẵắặâầẩẫấậèẻẽéẹêềểễếệìỉĩíịòỏõóọồổỗốơờởỡớợùủũúụưừửữứựỳỷỹýỵ]+$/i,
+          otherLatinLetters: /^[āēīōūéñ]+$/i,
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Bitte alle Sprachen bis auf deutsch wieder rauswerfen.

Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Und die Liste bitte alphabetisch sortieren...

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 3]
```diff
@@ -89,7 +89,69 @@ export class ProcessSolutionPanel {
...
+            if (letter.match(regExpList[regEx])) {
+              letterIsInvalid = false;
+              break;
+            }
+          }
+
+          if (letterIsInvalid) {
+            return false;
+          }
+        }
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Ich denke wir könnten das so in etwa schreiben:

```ts
const containsInvalidCharacter: boolean = inputAsCharArray.some( letter: string => 
{
  return regExpList.some( regEx => return letter.match(regEx); );
});
```

Das würde den code einfacher machen.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 4]
```diff
@@ -89,7 +89,69 @@ export class ProcessSolutionPanel {
...
+
+        return true;
+      })
+      .withMessage('The diagram name must be alphanumeric');
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Ich würde die Nachricht vorschlagen:

`The diagram name did not pass the imput validation. Please consult the manual for valid names (LINK).`

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 5]
```diff
@@ -438,6 +500,15 @@ export class ProcessSolutionPanel {
       return;
     }
 
+    const alphanumericRegEx: RegExp = /^[a-z0-9äöüÄÖÜß]+$/i;
+    const processNameIsNotAlphanumeric: boolean = processName.match(alphanumericRegEx) === null;
+
+    if (processNameIsNotAlphanumeric) {
+      this._notificationService.showNotification(NotificationType.ERROR, 'The diagram name must be alphanumeric');
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Sowas ist eigentlich kein Fehler.

Das ist höchstens eine Warning, eher eine Info, mit dem Zusatz:

`(...) Please correct the name and save again.`

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 6]
```diff
@@ -421,7 +443,7 @@ export class ProcessSolutionPanel {
 
     const processNameIsEmpty: boolean = processName.length === 0;
     if (processNameIsEmpty) {
-      this._notificationService.showNotification(NotificationType.ERROR, 'Process model name cannot be empty.');
+      this._notificationService.showNotification(NotificationType.INFO, 'Process model name cannot be empty.');
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Besser wäre:

"Process Model name must not be empty."

Das heißt dann übersetzt: darf nicht leer sein.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 7]
```diff
@@ -433,7 +455,26 @@ export class ProcessSolutionPanel {
 
     const diagramWithIdAlreadyExists: boolean = foundDiagram !== undefined;
     if (diagramWithIdAlreadyExists) {
-      this._notificationService.showNotification(NotificationType.ERROR, 'A diagram with that name already exists.');
+      this._notificationService.showNotification(NotificationType.INFO, 'A diagram with that name already exists.');
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Was ist die Konsequenz daraus? 

Bitte beschreiben, z.b. so:

`'A diagram with that name already exists, saving aborted. Please specify a different name.');

Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Weiß nur nich ob das passt ;)

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 8]
```diff
@@ -433,7 +455,26 @@ export class ProcessSolutionPanel {
...
+
+      return;
+    }
+
+    const processNameAsCharArray: Array<string> = processName.split('');
```
Comment (cmg-dev) [inline src/modules/process-solution-panel/process-solution-panel.ts]: 👍

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 9]
```diff
@@ -77,6 +78,10 @@ export class ProcessSolutionPanel {
   private _identity: IIdentity;
   private _solutionExplorerIdentity: IIdentity;
   private _dropBehaviour: EventListener;
+  private _diagramValidationRegExpList: IUserInputValidationRule = {
+    alphanumeric: /^[a-z0-9]+$/i,
+    german: /^[äöüß]+$/i,
```
Comment (LeoTT) [inline src/modules/process-solution-panel/process-solution-panel.ts]: How about special chars like `_`, `-` and whitespace? More specifically a seperator, so the user is not restricted to camelCase.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 10]
```diff
@@ -433,7 +455,27 @@ export class ProcessSolutionPanel {
...
+        if (letter.match(this._diagramValidationRegExpList[regExIndex]) !== null) {
+          return false;
+        }
+      }
+
+      return true;
+    });
+
+    if (containsInvalidCharacter) {
+      const infoMessage: string = 'The diagram name contains invalid characters. Please correct the name and try again.';
```
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Currently only alphanumeric and german umlaute are allowed. Showing which characters were invalid is almost impossible. But I could add something like:
```only alphanumeric and german umlaute are allowed```

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 11]
```diff
@@ -89,7 +94,24 @@ export class ProcessSolutionPanel {
...
+            }
+          }
+
+          return true;
+        });
+
+        return containsNoInvalidCharacter;
+      })
+      // TODO: Replace (LINK) with a link to the documentation, where the user can see how a valid name must look like
+      .withMessage('The diagram name did not pass the imput validation. Please consult the manual for valid names (LINK).');
```
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: The Link is still missing because there is no documentation for that at the moment.

[the remark this answers is not in the document]
Comment (Vyperus) [reply src/modules/process-solution-panel/process-solution-panel.ts]: @SteffenKn Please open a PR in the documentation describing this. And then link that PR in this PR so we can see the documentation is updatet as well.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 12]
```diff
@@ -89,7 +94,24 @@ export class ProcessSolutionPanel {
...
+          for (const regExIndex in this._diagramValidationRegExpList) {
+            if (letter.match(this._diagramValidationRegExpList[regExIndex]) !== null) {
+              return false;
+            }
+          }
+
+          return true;
+        });
+
+        return containsNoInvalidCharacter;
```
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: This won't work since diagramValidationRegExpList is not an array

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 13]
```diff
@@ -89,7 +94,24 @@ export class ProcessSolutionPanel {
 
         return diagramWithIdDoesNotExists;
       })
-      .withMessage('A diagram with that name already exists.');
+      .withMessage('A diagram with that name already exists.')
+      .satisfies((input: string) => {
+        const inputAsCharArray: Array<string> = input.split('');
+
+        const containsNoInvalidCharacter: boolean = !inputAsCharArray.some((letter: string) => {
```
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: As far as I know, @cmg-dev prefers 'containsNoInvalidCharacter' to '!containsInvalidCharacter'.
If this is not the case, I will change this.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 14]
```diff
@@ -433,7 +455,27 @@ export class ProcessSolutionPanel {
...
+
+    const containsInvalidCharacter: boolean = processNameAsCharArray.some((letter: string) => {
+      for (const regExIndex in this._diagramValidationRegExpList) {
+        if (letter.match(this._diagramValidationRegExpList[regExIndex]) !== null) {
+          return false;
+        }
+      }
+
+      return true;
+    });
```
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: `for of` won't work either

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (LeoTT) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Not tested, but something like this could do it:
```ts
const invalidLetters: Array<string> = inputAsCharArray.filter((letter: string) => {
  
  const letterIsInvalid: boolean = this._diagramValidationRegExpList.some((regExp: RegExp) => {
    return letter.match(regExp) === null;
  });

  return letterIsInvalid;  
})
const containsInvalidCharacter: boolean = invalidLetters !== undefined && invalidLetters.length > 0;
```

With ```invalidLetters.reduce((acc, current) => `${acc}, '${current}'`,'').substring(2);``` you can create a nice string out of the list.

[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: Ohh ok now i see what u meant with `You could show which characters were invalid.`. My fault. I can do that.

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: This is the best name I can come up with:
`diagramNamePassesNameChecks`

use it.

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: My suggestion will solve this.

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (cmg-dev) [reply src/modules/process-solution-panel/process-solution-panel.ts]: This is a good suggestion. We should do it, but in a separate feature.

This is now only doing a lean bugfix with a little bit of foresight.

Please create an issue and link to this comment.

[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: https://github.com/process-engine/bpmn-studio/issues/823

File: src/modules/process-solution-panel/process-solution-panel.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.ts]: @Vyperus I added the link to the info message that occurs when you try to create the diagram with the invalid letters, because I could not find a nice way to display the link in the validation message.
Is that ok or do you know a better way to handle that?

@cmg-dev

File: src/modules/process-solution-panel/process-solution-panel.html [hunk 15]
```diff
@@ -58,7 +58,7 @@
             <div class="solution-diagram-group__entry">
               <input ref="solution.createNewDiagramInput" type="text" value.bind="solution.currentDiagramInputValue & validateOnChange">
               <ul if.bind="solution.errors && solution.errors.length > 0">
-                <li class="solution-error-message" repeat.for="error of solution.errors">${error.message}</li>
+                <span class="solution-error-message" repeat.for="error of solution.errors">${error.message}</span>
```
Comment (LeoTT) [inline src/modules/process-solution-panel/process-solution-panel.html]: Why is the above an `ul`(considering there are no `li`s anymore).
Should be template or div if necessary.

File: src/modules/process-solution-panel/process-solution-panel.ts [hunk 16]
```diff
@@ -433,7 +455,31 @@ export class ProcessSolutionPanel {
...
+
+    if (containsInvalidCharacter) {
+      const infoMessage: string = 'The diagram name contains invalid characters. Please correct the name and try again.'
+                                + ` <a href="javascript:nodeRequire('open')
+                                   ('https://www.process-engine.io/documentation/bpmn-studio/components/solution-explorer/solution-explorer.html')">
+                                   Click here to see which letters are valid.
+                                   </a>`;
```
Comment (LeoTT) [inline src/modules/process-solution-panel/process-solution-panel.ts]: Template strings carry the linebreaks and indentation. In this case it might go unnoticed but just to be safe I would not do it that way.
```ts
const documentationLink: string = 'https://www.process-engine.io/documentation/bpmn-studio/components/solution-explorer/solution-explorer.html';
... = `<a href="javascript:nodeRequire('open')('${documentationLink}')">`
        + 'Click here to see which letters are valid.'
        + '</a>';
```

File: src/modules/process-solution-panel/process-solution-panel.html (hunk 15 above)
Comment (SteffenKn) [reply src/modules/process-solution-panel/process-solution-panel.html]: This was a mistake should be `li`
