### PR TITLE
⬆️ :arrow_up: Upgrade jquery, 💄 :lipstick: Fix indent

### LINKED ISSUE #142: Potential Security Issue JQuery
#### Describe your issue

The jQuery version is ^2.2.4.
This causes a potential Security Issue.

#### How can others reproduce the issue?

bildschirmfoto 2018-01-24 um 13 38 59

#### Possible solution

Update to ^3.0.0 and check if everything is working correctly.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by alexanderkasten**
## What did you change?

This PR just upgrades jquery from `^2.2.4` to `^3.0.0` and fixes some style.
Closes #142 

## How can others test the changes?

- `rm -rf node_modules/`
- `npm i`
- `au run`
 and see that all works correctly.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

File: src/modules/processdef-detail/processdef-detail.ts [hunk 1]
```diff
@@ -137,11 +137,13 @@ export class ProcessDefDetail {
 
   public exportBPMN(): void {
     this.disableAndHideControlsForImageExport();
-    this.bpmn.getXML().then((xml: string) => {
+
+    this.bpmn.getXML()
+    .then((xml: string) => {
```
Comment (heikomat) [inline src/modules/processdef-detail/processdef-detail.ts]: We use typescript. you can use async/await

Comment (cmg-dev) [reply src/modules/processdef-detail/processdef-detail.ts]: @heikomat 

> can use async/await

or

> should use async/await

or 

> USE! async/await
