### PR TITLE
🐛Fix double-click on Windows

### LINKED ISSUE #646: A new BPMN Studio instance opens when double clicking a process definition
#### Describe your issue
When double clicking on a bpmn process definition, a new instance of the BPMN Studio opens and only shows the process definition view instead of the double clicked process. 

That only the Process List view open, when you double click a bpmn process definition also happens,
when the bpmn studio was not running before.

jul-26-2018 14-02-22

#### How can others reproduce the issue?
* Open BPMN Studio
* Double Click on a bpmn process definition
* See, that a new instance of the bpmn studio gets created

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #806: 🐛 BPMN File can only be opened via double click, if BPMN Studio is not running
Funktioniert auf Windows nur wenn das BPMN-Studio geschlossen ist.

### PR DESCRIPTION
**Pull request by Vyperus**
:tada: **Thanks for submitting this Pull Request**

Please provide a list including your changes.

To help us to create a meaningful Changelog, we agreed 
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.

Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:

---

**Changes:**

1. Add double-click handling for Windows

**Issues:**

Closes #806
Closes #646 

PR: #PullRequest

---

See the [examples](#example) for inspiration.

## How can others test the changes?

> Describe how others can test your changes (you can remove this section for typo fixes etc.)

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: electron_app/electron.js [hunk 1]
```diff
@@ -17,32 +17,64 @@ let filePath;
...
+   * This method gets called when BPMN-Studio starts the first time. When it
+   * starts the first time it's the first instance, therefore this functions
+   * returns "false" and the following if-clause will start BPMN-Studio.
+   * If you double-click a .bpmn file now the call back will be called again,
+   * but this time "argv" will hold the command line arguments the second
+   * instance would have been started with.
+   * Since this would be the second instance the method in the second instance
+   * will return "true" and therefore quit the instance. But the callback of
+   * the firstinstance allows us to send the double-click event to the renderer
+   * process and finally open a file via double-click.
```
Comment (cmg-dev) [inline electron_app/electron.js]: 👍 great comment.

File: electron_app/electron.js [hunk 2]
```diff
@@ -17,32 +17,65 @@ let filePath;
...
+   * and the following if-clause will start BPMN-Studio.
+   *
+   * If you double-click on a .bpmn file, the callback will be called again,
+   * but this time "argv" will hold the command line arguments the second
+   * instance would have been started with.
+   *
+   * Since this would be the second instance the method in the second instance
+   * will return "true" and therefore quit the instance. The callback of the 
+   * first instance allows us to send the double-click event to the renderer
+   * process and finally open a file via double-click.
```
Comment (cmg-dev) [inline electron_app/electron.js]: 👍 Great Comment.
